### PR TITLE
x86, cfi: fix objtool warnings around copy_user() and clear_page()

### PR DESCRIPTION
**Pull request by solbjorn**
```
Both of these uses alternative_call_2() under the hood, which calls
alternatives from inline assembly.
All of the alternatives are ASM, not C, and aren't called anywhere
from C code, so their declarations can be converted to opaque to
eliminate dozens of objtool warnings and make object code smaller.
```

### CODE REVIEW

**Comment by solbjorn** [comment]
My cheatsheet about what is left unaddressed:

```
#
# Most of these get passed to the asm inline code, that should be the reason
#
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.76536+0xfffffffffffffffd
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.76536+0x5
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.76536+0x1d
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.74135+0xfffffffffffffffd
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.76536+0x25
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.76536+0x2d
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.76536+0x35
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.76536+0x3d
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.76536+0x55
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.76536+0x5d
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.76536+0x65
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.76536+0x6d
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.76536+0x7d
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.76536+0x85
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.76536+0x8d
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.76536+0x95
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.76536+0x9d
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.74135+0x5
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.76536+0xa5
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.76536+0xad
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.76536+0xb5
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.76536+0xcd
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.80507+0x6f5
vmlinux.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.80507+0x6f5
vmlinux.o: warning: objtool: sysvec_xen_hvm_callback()+0x93: can't find call dest symbol at .text..L.cfi.jumptable.76536+0x8
vmlinux.o: warning: objtool: sysvec_hyperv_reenlightenment()+0x93: can't find call dest symbol at .text..L.cfi.jumptable.76536+0x20
vmlinux.o: warning: objtool: common_interrupt()+0xa3: can't find call dest symbol at .text..L.cfi.jumptable.74135+0x0
vmlinux.o: warning: objtool: sysvec_x86_platform_ipi()+0x93: can't find call dest symbol at .text..L.cfi.jumptable.76536+0x28
vmlinux.o: warning: objtool: sysvec_kvm_posted_intr_wakeup_ipi()+0x93: can't find call dest symbol at .text..L.cfi.jumptable.76536+0x30
vmlinux.o: warning: objtool: sysvec_thermal()+0x93: can't find call dest symbol at .text..L.cfi.jumptable.76536+0x38
vmlinux.o: warning: objtool: sysvec_irq_work()+0x93: can't find call dest symbol at .text..L.cfi.jumptable.76536+0x40
vmlinux.o: warning: objtool: sysvec_deferred_error()+0x93: can't find call dest symbol at .text..L.cfi.jumptable.76536+0x58
vmlinux.o: warning: objtool: sysvec_threshold()+0x93: can't find call dest symbol at .text..L.cfi.jumptable.76536+0x60
vmlinux.o: warning: objtool: sysvec_hyperv_callback()+0x93: can't find call dest symbol at .text..L.cfi.jumptable.76536+0x68
vmlinux.o: warning: objtool: sysvec_hyperv_stimer0()+0x93: can't find call dest symbol at .text..L.cfi.jumptable.76536+0x70
vmlinux.o: warning: objtool: sysvec_acrn_hv_callback()+0x93: can't find call dest symbol at .text..L.cfi.jumptable.76536+0x80
vmlinux.o: warning: objtool: sysvec_reboot()+0x46: can't find call dest symbol at .text..L.cfi.jumptable.76536+0x88
vmlinux.o: warning: objtool: sysvec_call_function()+0x93: can't find call dest symbol at .text..L.cfi.jumptable.76536+0x90
vmlinux.o: warning: objtool: sysvec_call_function_single()+0x93: can't find call dest symbol at .text..L.cfi.jumptable.76536+0x98
vmlinux.o: warning: objtool: sysvec_apic_timer_interrupt()+0x93: can't find call dest symbol at .text..L.cfi.jumptable.76536+0xa0
vmlinux.o: warning: objtool: spurious_interrupt()+0xa3: can't find call dest symbol at .text..L.cfi.jumptable.74135+0x8
vmlinux.o: warning: objtool: sysvec_spurious_apic_interrupt()+0x93: can't find call dest symbol at .text..L.cfi.jumptable.76536+0xa8
vmlinux.o: warning: objtool: sysvec_error_interrupt()+0x93: can't find call dest symbol at .text..L.cfi.jumptable.76536+0xb0
vmlinux.o: warning: objtool: sysvec_irq_move_cleanup()+0x93: can't find call dest symbol at .text..L.cfi.jumptable.76536+0xb8
vmlinux.o: warning: objtool: sysvec_kvm_asyncpf_interrupt()+0x93: can't find call dest symbol at .text..L.cfi.jumptable.76536+0xd0
vmlinux.o: warning: objtool: __local_bh_enable_ip()+0xc1: can't find call dest symbol at .text..L.cfi.jumptable.80507+0x6f8
vmlinux.o: warning: objtool: do_softirq()+0x74: can't find call dest symbol at .text..L.cfi.jumptable.80507+0x6f8
vmlinux.o: warning: objtool: sysvec_reboot()+0x62: sibling call from callable instruction with modified stack frame

#
# get_bh() -> atomic_inc() -> arch__atomic_int(). x86's version uses asm
# alternatives with .smp_locks section, no idea how to WA
#
fs/udf/udf.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.273+0xfffffffffffffffd
fs/udf/udf.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.273+0xfffffffffffffffd
fs/udf/udf.lto.o: warning: objtool: udf_table_prealloc_blocks()+0x275: can't find call dest symbol at .text..L.cfi.jumptable.273+0x0
fs/udf/udf.lto.o: warning: objtool: udf_new_block()+0x36d: can't find call dest symbol at .text..L.cfi.jumptable.273+0x0
fs/udf/udf.lto.o: warning: objtool: udf_table_prealloc_blocks()+0x1e5: stack state mismatch: cfa1=4+144 cfa2=4+152
fs/udf/udf.lto.o: warning: objtool: udf_new_block()+0x306: stack state mismatch: cfa1=4+192 cfa2=4+200

#
# Something about passing the entire structure as an argument, not the pointer
# to it. Weird
#
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.3686+0xfffffffffffffffd
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.3686+0xfffffffffffffffd
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.3686+0xfffffffffffffffd
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.3686+0xfffffffffffffffd
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.3686+0xfffffffffffffffd
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.3686+0xfffffffffffffffd
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.3686+0xfffffffffffffffd
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.3686+0xfffffffffffffffd
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.3686+0xfffffffffffffffd
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: mlx5e_deactivate_priv_channels()+0xb0: can't find call dest symbol at .text..L.cfi.jumptable.3686+0x0
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: mlx5e_set_rxfh()+0x154: can't find call dest symbol at .text..L.cfi.jumptable.3686+0x0
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: mlx5e_xsk_setup_pool()+0x2fa: can't find call dest symbol at .text..L.cfi.jumptable.3686+0x0
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: mlx5e_xsk_setup_pool()+0x4a3: can't find call dest symbol at .text..L.cfi.jumptable.3686+0x0
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: mlx5e_xsk_redirect_rqt_to_channel()+0x5f: can't find call dest symbol at .text..L.cfi.jumptable.3686+0x0
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: mlx5e_xsk_redirect_rqt_to_drop()+0x5a: can't find call dest symbol at .text..L.cfi.jumptable.3686+0x0
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: mlx5e_xsk_redirect_rqts_to_channels()+0xc9: can't find call dest symbol at .text..L.cfi.jumptable.3686+0x0
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: mlx5e_xsk_redirect_rqts_to_channels()+0x178: can't find call dest symbol at .text..L.cfi.jumptable.3686+0x0
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: mlx5e_xsk_redirect_rqts_to_drop()+0xaa: can't find call dest symbol at .text..L.cfi.jumptable.3686+0x0
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: mlx5e_deactivate_priv_channels()+0x40: stack state mismatch: cfa1=4+104 cfa2=4+112
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: mlx5e_set_rxfh()+0x15d: stack state mismatch: cfa1=4+96 cfa2=4+104
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: mlx5e_xsk_setup_pool()+0x513: stack state mismatch: cfa1=4+120 cfa2=4+128
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: mlx5e_xsk_redirect_rqt_to_channel()+0x7c: return with modified stack frame
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: mlx5e_xsk_redirect_rqt_to_drop()+0x77: return with modified stack frame
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: mlx5e_xsk_redirect_rqts_to_channels()+0xea: stack state mismatch: cfa1=4+88 cfa2=4+96
drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.lto.o: warning: objtool: mlx5e_xsk_redirect_rqts_to_drop()+0x40: stack state mismatch: cfa1=4+72 cfa2=4+80
sound/soc/intel/skylake/snd-soc-skl.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.670+0xfffffffffffffffd
sound/soc/intel/skylake/snd-soc-skl.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.670+0xfffffffffffffffd
sound/soc/intel/skylake/snd-soc-skl.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.670+0xfffffffffffffffd
sound/soc/intel/skylake/snd-soc-skl.lto.o: warning: objtool: skl_sst_dsp_init()+0x49: can't find call dest symbol at .text..L.cfi.jumptable.670+0x0
sound/soc/intel/skylake/snd-soc-skl.lto.o: warning: objtool: bxt_sst_dsp_init()+0x49: can't find call dest symbol at .text..L.cfi.jumptable.670+0x0
sound/soc/intel/skylake/snd-soc-skl.lto.o: warning: objtool: cnl_sst_dsp_init()+0x49: can't find call dest symbol at .text..L.cfi.jumptable.670+0x0
sound/soc/intel/skylake/snd-soc-skl.lto.o: warning: objtool: skl_sst_dsp_init()+0x19b: return with modified stack frame
sound/soc/intel/skylake/snd-soc-skl.lto.o: warning: objtool: bxt_sst_dsp_init()+0x222: return with modified stack frame
sound/soc/intel/skylake/snd-soc-skl.lto.o: warning: objtool: cnl_sst_dsp_init()+0x1bf: return with modified stack frame

#
# No idea at all
#
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18445+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18445+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18446+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18541+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18544+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18542+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18542+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18543+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18541+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18546+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18545+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18541+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18544+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18542+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18542+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18543+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18541+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18546+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18545+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18541+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18544+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18542+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18542+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18543+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18541+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18546+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18545+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18541+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18544+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18542+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18542+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18543+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18541+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18546+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18545+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: can't find a CFI jump table relocation at .text..L.cfi.jumptable.18685+0xfffffffffffffffd
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dwb2_set_scaler()+0x2a5: can't find call dest symbol at .text..L.cfi.jumptable.18445+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dwb2_set_scaler()+0x2fb: can't find call dest symbol at .text..L.cfi.jumptable.18445+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dwb2_set_scaler()+0x350: can't find call dest symbol at .text..L.cfi.jumptable.18446+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml20_rq_dlg_get_rq_reg()+0x391: can't find call dest symbol at .text..L.cfi.jumptable.18541+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml20_rq_dlg_get_rq_reg()+0x44c: can't find call dest symbol at .text..L.cfi.jumptable.18544+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: extract_rq_regs()+0x5a: can't find call dest symbol at .text..L.cfi.jumptable.18542+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: extract_rq_regs()+0x1c1: can't find call dest symbol at .text..L.cfi.jumptable.18542+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml20_rq_dlg_get_dlg_reg()+0x20e: can't find call dest symbol at .text..L.cfi.jumptable.18543+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml20_rq_dlg_get_dlg_reg()+0x511: can't find call dest symbol at .text..L.cfi.jumptable.18541+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml20_rq_dlg_get_dlg_params()+0x502e: can't find call dest symbol at .text..L.cfi.jumptable.18546+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml20_rq_dlg_get_dlg_params()+0x505b: can't find call dest symbol at .text..L.cfi.jumptable.18545+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml20v2_rq_dlg_get_rq_reg()+0x391: can't find call dest symbol at .text..L.cfi.jumptable.18541+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml20v2_rq_dlg_get_rq_reg()+0x44c: can't find call dest symbol at .text..L.cfi.jumptable.18544+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: extract_rq_regs.14791()+0x5a: can't find call dest symbol at .text..L.cfi.jumptable.18542+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: extract_rq_regs.14791()+0x1c1: can't find call dest symbol at .text..L.cfi.jumptable.18542+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml20v2_rq_dlg_get_dlg_reg()+0x20e: can't find call dest symbol at .text..L.cfi.jumptable.18543+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml20v2_rq_dlg_get_dlg_reg()+0x511: can't find call dest symbol at .text..L.cfi.jumptable.18541+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml20v2_rq_dlg_get_dlg_params()+0x4fe6: can't find call dest symbol at .text..L.cfi.jumptable.18546+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml20v2_rq_dlg_get_dlg_params()+0x5013: can't find call dest symbol at .text..L.cfi.jumptable.18545+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml21_rq_dlg_get_rq_reg()+0x5e8: can't find call dest symbol at .text..L.cfi.jumptable.18541+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml21_rq_dlg_get_rq_reg()+0x6aa: can't find call dest symbol at .text..L.cfi.jumptable.18544+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: extract_rq_regs.14976()+0x5a: can't find call dest symbol at .text..L.cfi.jumptable.18542+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: extract_rq_regs.14976()+0x1c1: can't find call dest symbol at .text..L.cfi.jumptable.18542+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml21_rq_dlg_get_dlg_reg()+0x207: can't find call dest symbol at .text..L.cfi.jumptable.18543+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml21_rq_dlg_get_dlg_reg()+0x74e: can't find call dest symbol at .text..L.cfi.jumptable.18541+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml_rq_dlg_get_dlg_params()+0x5223: can't find call dest symbol at .text..L.cfi.jumptable.18546+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml_rq_dlg_get_dlg_params()+0x5255: can't find call dest symbol at .text..L.cfi.jumptable.18545+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml30_rq_dlg_get_rq_reg()+0x4ab: can't find call dest symbol at .text..L.cfi.jumptable.18541+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml30_rq_dlg_get_rq_reg()+0x56d: can't find call dest symbol at .text..L.cfi.jumptable.18544+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: extract_rq_regs.15220()+0x5a: can't find call dest symbol at .text..L.cfi.jumptable.18542+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: extract_rq_regs.15220()+0x1c1: can't find call dest symbol at .text..L.cfi.jumptable.18542+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml30_rq_dlg_get_dlg_reg()+0x206: can't find call dest symbol at .text..L.cfi.jumptable.18543+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml30_rq_dlg_get_dlg_reg()+0x61d: can't find call dest symbol at .text..L.cfi.jumptable.18541+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml_rq_dlg_get_dlg_params.15264()+0x567b: can't find call dest symbol at .text..L.cfi.jumptable.18546+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dml_rq_dlg_get_dlg_params.15264()+0x56ad: can't find call dest symbol at .text..L.cfi.jumptable.18545+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dc_create_resource_pool()+0xdd: can't find call dest symbol at .text..L.cfi.jumptable.18685+0x0
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dwb2_set_scaler()+0x359: stack state mismatch: cfa1=4+64 cfa2=4+80
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: dc_create_resource_pool()+0x239: stack state mismatch: cfa1=4+16 cfa2=4+24
```

**Comment by samitolvanen** [comment]
Thanks for looking into this!

One issue here appears to be that we end up with `_PC32` and `_PLT32` relocations that refer to jump table sections, which confuses objtool because it's unable to resolve them . The objtool patch in my tree also currently just blindly uses the `addend` for section references despite the relocation type, which obviously fails for these.

**Comment by samitolvanen** [comment]
I folded this change into commit 6d171dc125b6dcbfd30849099c64381e292de769 with a Suggested-by tag. The latest push attempts to address the other objtool issues too, but requires more testing, and probably more tweaking as well.

**Comment by solbjorn** [comment]
Great, thanks! I'll test the latest revision soon and report.

**Comment by solbjorn** [comment]
Not a single objtool warning regarding jumps and relocations, both from vmlinux.o and all the modules, and the kernel works perfectly fine, great!

Seems like there's only one issue left, at least on my setup. kallsyms are still messed for `.cfi_jt` symbols:

```
? __x64_sys_openat2.cfi_jt+0x8/0x8
```

_(I know it's still WIP)_

**Comment by samitolvanen** [comment]
> Seems like there's only one issue left, at least on my setup. kallsyms are still messed for `.cfi_jt` symbols:
> 
> ```
> ? __x64_sys_openat2.cfi_jt+0x8/0x8
> ```
> 
> _(I know it's still WIP)_

Thanks, I'll take a look. I'm hoping we won't need that patch and can fix the issue with missing .cfi_jt symbols in LLVM instead.

**Pull request closed without merging**
